# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YjEwNGMxNmE1NDdmYzQyMTY2OWU1OGRhNjlkYzFjMmE3NWUxYjE3ZWUwYjdhMDk2OGE0YzI4YzBkNzkzY2ExYzliNWUzNzEwMThhM2NmNjNiZmQxNmE5MWJhZDIyYjA2YTA0ODc1ODIyYmZjZDRjNWI1MTBkNzFlYTMwNTc1ODY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
